x-test-env: &test-env
  POSTGRES_DB: ${POSTGRES_TEST_DB}
  USE_MOCK_STL_CONN: true
  USE_MOCK_NEXUS: true
  USE_MOCK_STARPROBE: true
services:
  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_TEST_DB}
    volumes: !override []

  obs-api:
    build:
      target: development
    ports: !override
      - "${HOST_BIND_IP}:${TEST_PORT}:8000"
    environment:
      <<: *test-env

  worker:
    build:
      target: development
    environment:
      <<: *test-env
