services:
  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_TEST_DB}
    volumes: !override []

  obs-api:
    build:
      target: development
    ports: !override
      - "${HOST_BIND_IP}:${TEST_PORT}:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_TEST_DB}

  celery-worker:
    build:
      target: development
    command: celery -A src.obs_graphs.celery.app worker --loglevel=debug
    environment:
      - POSTGRES_DB=${POSTGRES_TEST_DB}
