x-test-env: &test-env
  POSTGRES_DB: ${POSTGRES_TEST_DB}
  OBS_GLX_USE_MOCK_STL_CONN: true
  OBS_GLX_USE_MOCK_NEXUS: true
  OBS_GLX_USE_MOCK_STARPROBE: true
services:
  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_TEST_DB}
    volumes: !override []

  obs-glx-api:
    build:
      target: development
    ports: !override
      - "${OBS_GLX_HOST_BIND_IP}:${OBS_GLX_TEST_PORT}:8000"
    environment:
      <<: *test-env

  obs-glx-worker:
    build:
      target: development
    environment:
      <<: *test-env
