services:
  db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}

  obs-api:
    build:
      target: development
    ports: !override
      - "${HOST_BIND_IP}:${TEST_PORT}:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      USE_MOCK_LLM: true
      USE_MOCK_GITHUB: true
      USE_MOCK_REDIS: true
      USE_MOCK_OLLAMA_DEEP_RESEARCHER: true

  celery-worker:
    build:
      target: development
    command: celery -A src.tasks.celery_app worker --loglevel=debug
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      USE_MOCK_LLM: true
      USE_MOCK_GITHUB: true
      USE_MOCK_REDIS: true
      USE_MOCK_OLLAMA_DEEP_RESEARCHER: true
