services:
  db:
    environment:
      POSTGRES_DB: ${POSTGRES_DEV_DB}

  obs-api:
    build:
      target: development
    ports: !override
      - "${HOST_BIND_IP}:${DEV_PORT}:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DEV_DB}
    volumes:
      - .:/app
      - /app/.venv

  celery-worker:
    build:
      target: development
    environment:
      POSTGRES_DB: ${POSTGRES_DEV_DB}
    volumes:
      - .:/app
      - /app/.venv
