services:
  research-api:
    build:
      context: ./submodules/ollama-deep-researcher
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    environment:
      CONTAINER_ENV: production
      OLLAMA_HOST: ${OLLAMA_HOST}
      RESEARCH_API_OLLAMA_MODEL: ${RESEARCH_API_OLLAMA_MODEL:-llama3.2:3b}
      TAVILY_API_KEY: ${TAVILY_API_KEY:-}
    networks:
      backend:
        aliases:
          - research-api
    healthcheck:
      test: ["CMD", "python", "-c", "import sys, urllib.request; sys.exit(0) if urllib.request.urlopen('http://localhost:8000/health').getcode() == 200 else sys.exit(1)"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 5
