services:
  db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}

  obs-api:
    build:
      target: development
      args:
        OLLAMA_DEEP_RESEARCHER_GITHUB_TOKEN: ${OLLAMA_DEEP_RESEARCHER_GITHUB_TOKEN}
    ports: !override
      - "${HOST_BIND_IP}:${TEST_PORT}:8000"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      OBS_GRAPHS_OLLAMA_MODEL: ${OBS_GRAPHS_OLLAMA_MODEL}
    depends_on:
      research-api:
        condition: service_healthy

  celery-worker:
    depends_on:
      research-api:
        condition: service_healthy
