name: CI Workflows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-linters:
    uses: ./.github/workflows/run-linters.yml

  run-local-tests:
    uses: ./.github/workflows/run-local-tests.yml

  run-docker-tests:
    uses: ./.github/workflows/run-docker-tests.yml
    secrets:
      OBS_GRAPHS_TOKEN: ${{ secrets.OBS_GRAPHS_TOKEN }}
      OBSIDIAN_VAULT_REPOSITORY: ${{ secrets.OBSIDIAN_VAULT_REPOSITORY }}
