name: CI Workflows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-linters:
    uses: ./.github/workflows/run-linters.yml
    secrets:
      OBS_GLX_TOKEN: ${{ secrets.OBS_GLX_TOKEN }}

  run-local-tests:
    uses: ./.github/workflows/run-local-tests.yml
    secrets:
      OBS_GLX_TOKEN: ${{ secrets.OBS_GLX_TOKEN }}

  run-docker-tests:
    uses: ./.github/workflows/run-docker-tests.yml
    secrets:
      OBS_GLX_TOKEN: ${{ secrets.OBS_GLX_TOKEN }}
