name: Push Image to GHCR

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push main image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/asterismhq/obs-glx-api:latest

      - name: Build and push worker image
        uses: docker/build-push-action@v5
        with:
          context: ./worker/obs_glx_worker
          push: true
          tags: ghcr.io/asterismhq/obs-glx-worker:latest