name: Run Linters

on:
  workflow_call:
    secrets:
      OBS_GLX_TOKEN:
        required: true

jobs:
  run-linters:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      UV_CACHE_DIR: ./.uv-cache
      OBS_GLX_TOKEN: ${{ secrets.OBS_GLX_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          dependency-command: 'uv sync --frozen'
          git-token: ${{ secrets.OBS_GLX_TOKEN }}

      - name: Configure SQLite for testing
        run: echo "OBS_GLX_USE_SQLITE=true" >> .env
        shell: bash

      - name: Run Linters
        run: just lint