name: Run Local Tests

on:
  workflow_call:
    secrets:
      OLLAMA_HOST:
        required: true

permissions:
  contents: read

jobs:
  run-local-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_target: [unit, sqlt]
    env:
      OBSIDIAN_VAULT_GITHUB_TOKEN: ${{ secrets.VAULT_GITHUB_TOKEN }}
      OLLAMA_DEEP_RESEARCHER_GITHUB_TOKEN: ${{ secrets.OLLAMA_DEEP_RESEARCHER_GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies
        run: uv sync --frozen

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Create .env file for CI
        run: cp .env.example .env

      - name: Run local tests
        env:
          USE_SQLITE: "true"
        run: just ${{ matrix.test_target }}-test