name: Run Docker Tests

on:
  workflow_call:
    secrets:
      OLLAMA_HOST:
        required: true
      OBS_GRAPHS_TOKEN:
        required: true
      OBSIDIAN_VAULT_REPOSITORY:
        required: true

permissions:
  contents: read

jobs:
  run-docker-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_target: [build-test, psql-test, e2e-test]
    env:
      OLLAMA_HOST: ${{ secrets.OLLAMA_HOST }}
      OBS_GRAPHS_TOKEN: ${{ secrets.OBS_GRAPHS_TOKEN }}
      OBSIDIAN_VAULT_REPOSITORY: ${{ secrets.OBSIDIAN_VAULT_REPOSITORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.OBS_GRAPHS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies
        run: uv sync --frozen

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Create .env file for CI
        run: cp .env.example .env

      - name: Run docker tests (USE_SQLITE=false)
        run: just ${{ matrix.test_target }}